#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d sh browser ide IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# use xprope to get name
bspc rule -a Alacritty desktop='^1'
bspc rule -a firefoxdeveloperedition focus=on desktop='^2'
bspc rule -a jetbrains-idea-ce desktop='^3'
bspc rule -a code-oss focus=on desktop='^3'
bspc rule -a polybar border=off manage=off

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
